// @flow
type Events = Array<{
	eventId: string,
	eventDate: string,
	eventGuests: number,
	eventType: string,
	eventRegion: string,
	eventSubmissionDate: string,
	eventFreeMessage: string,
	eventPurchases: number
}>;
type T = {
	eventId: string,
	eventDate: string,
	eventGuests: number,
	eventType: string,
	eventRegion: string,
	eventSubmissionDate: string,
	eventFreeMessage: string,
	eventPurchases: number
};
type User = {
	userId: string,
	name: string,
	email: string,
	companyName: string,
	number: string,
	subscriptionStartDate: string,
	subscriptionEndDate: string
};
type PurchasedEvents = Array<{
	eventId: string,
	eventDate: string,
	eventGuests: number,
	eventType: string,
	eventRegion: string,
	eventSubmissionDate: string,
	eventFreeMessage: string,
	eventPurchases: number,
	eventPurchaseDetails: {},
	contactName: string,
	contactEmail: string,
	contactNumber: string,
	contactAddress: string
}>;
type Favorite = Array<string>;

export const events: Events = [
  {
    eventId: 'eventcatering0001',
    eventDate: '14.12.2018',
    eventGuests: 15,
    eventType: 'TurnKey',
    eventRegion: 'Helsinki',
    eventSubmissionDate: '10.11.2018',
    eventFreeMessage: 'BirthDay Celebration',
    eventPurchases: 3,
  },
  {
    eventId: 'eventcatering0002',
    eventDate: '11.12.2018',
    eventGuests: 10,
    eventType: 'Just Catering',
    eventRegion: 'Vasaa',
    eventSubmissionDate: '19.11.2018',
    eventFreeMessage: 'House Warming Celebration',
    eventPurchases: 7,
  },
  {
    eventId: 'eventcatering0003',
    eventDate: '23.12.2018',
    eventGuests: 30,
    eventType: 'Space and Catering',
    eventRegion: 'Provoo',
    eventSubmissionDate: '14.11.2018',
    eventFreeMessage: 'Christmas Celebration',
    eventPurchases: 5,
  },
  {
    eventId: 'eventcatering0004',
    eventDate: '27.12.2018',
    eventGuests: 200,
    eventType: 'Catering and Program',
    eventRegion: 'Espoo',
    eventSubmissionDate: '15.11.2018',
    eventFreeMessage: 'Wedding Celebration',
    eventPurchases: 7,
  },
];

export const eventcatering0001: T = {
  eventId: 'eventcatering0001',
  eventDate: '14.12.2018',
  eventGuests: 15,
  eventType: 'TurnKey',
  eventRegion: 'Helsinki',
  eventSubmissionDate: '10.11.2018',
  eventFreeMessage: 'BirthDay Celebration',
  eventPurchases: 3,
};
export const eventcatering0002: T = {
  eventId: 'eventcatering0002',
  eventDate: '11.12.2018',
  eventGuests: 10,
  eventType: 'Just Catering',
  eventRegion: 'Vasaa',
  eventSubmissionDate: '19.11.2018',
  eventFreeMessage: 'House Warming Celebration',
  eventPurchases: 7,
};
export const eventcatering0003: T = {
  eventId: 'eventcatering0003',
  eventDate: '23.12.2018',
  eventGuests: 30,
  eventType: 'Space and Catering',
  eventRegion: 'Provoo',
  eventSubmissionDate: '14.11.2018',
  eventFreeMessage: 'Christmas Celebration',
  eventPurchases: 5,
};
export const eventcatering0004: T = {
  eventId: 'eventcatering0004',
  eventDate: '27.12.2018',
  eventGuests: 200,
  eventType: 'Catering and Program',
  eventRegion: 'Espoo',
  eventSubmissionDate: '15.11.2018',
  eventFreeMessage: 'Wedding Celebration',
  eventPurchases: 7,
};
export const individualUser: User = {
  userId: 'user251',
  name: 'John Smith',
  email: 'johnsmith@gmail.com',
  companyName: 'JS Catering Oy',
  number: '0458965814',
  subscriptionStartDate: '4.8.2018',
  subscriptionEndDate: '3.8.2019',
};
export const purchasedEvents: PurchasedEvents = [
  {
    eventId: 'eventcatering0004',
    eventDate: '27.12.2018',
    eventGuests: 200,
    eventType: 'Catering and Program',
    eventRegion: 'Espoo',
    eventSubmissionDate: '15.11.2018',
    eventFreeMessage: 'Wedding Celebration',
    eventPurchases: 7,
    eventPurchaseDetails: {},
    contactName: 'John Smith',
    contactEmail: 'johnsmith@gmail.com',
    contactNumber: '0458595631',
    contactAddress: 'Klippinkitie 5 A 45, 02780, Espoo',
  },
  {
    eventId: 'eventcatering0005',
    eventDate: '28.12.2018',
    eventGuests: 200,
    eventType: 'Catering',
    eventRegion: 'Espoo',
    eventSubmissionDate: '15.11.2018',
    eventFreeMessage: 'Birthday Celebration',
    eventPurchases: 7,
    eventPurchaseDetails: {},
    contactName: 'John Smith',
    contactEmail: 'johnsmith@gmail.com',
    contactNumber: '0458595631',
    contactAddress: 'Kilo 5 A 45, 02780, Espoo',
  },
  {
    eventId: 'eventcatering0006',
    eventDate: '28.12.2018',
    eventGuests: 200,
    eventType: 'Catering',
    eventRegion: 'Espoo',
    eventSubmissionDate: '15.11.2018',
    eventFreeMessage: 'Birthday Celebration',
    eventPurchases: 7,
    eventPurchaseDetails: {},
    contactName: 'John Smith',
    contactEmail: 'johnsmith@gmail.com',
    contactNumber: '0458595631',
    contactAddress: 'Kilo 5 A 45, 02780, Espoo',
  },
  {
    eventId: 'eventcatering0007',
    eventDate: '28.12.2018',
    eventGuests: 200,
    eventType: 'Catering',
    eventRegion: 'Espoo',
    eventSubmissionDate: '15.11.2018',
    eventFreeMessage: 'Birthday Celebration',
    eventPurchases: 7,
    eventPurchaseDetails: {},
    contactName: 'John Smith',
    contactEmail: 'johnsmith@gmail.com',
    contactNumber: '0458595631',
    contactAddress: 'Kilo 5 A 45, 02780',
  },
  {
    eventId: 'eventcatering0008',
    eventDate: '28.12.2018',
    eventGuests: 200,
    eventType: 'Catering',
    eventRegion: 'Espoo',
    eventSubmissionDate: '15.11.2018',
    eventFreeMessage: 'Birthday Celebration',
    eventPurchases: 7,
    eventPurchaseDetails: {},
    contactName: 'John Smith',
    contactEmail: 'johnsmith@gmail.com',
    contactNumber: '0458595631',
    contactAddress: 'Kilo 5 A 45, 02780, Espoo',
  },
];

export const Favorites: Favorite = ['eventcatering0001', 'eventcatering0002', 'eventcatering0004'];
