// @flow

export const START_FETCHING: string = 'START_FETCHING';
export const AUTHENTICATION_SUCCESS: string = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILS: string = 'AUTHENTICATION_FAILS';

export const SIGNUP_SUCCESS: string = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILS: string = 'SiGNUP_FAILS';

export const CHECK_USER: string = 'CHECK_USER';
export const LOG_OUT: string = 'LOG_OUT';

export const FETCH_EVENTS_LIST_SUCCESS: string = 'FETCH_EVENTS_LIST_SUCCESS';
export const FETCH_EVENTS_LIST_FAILS: string = 'FETCH_EVENTS_LIST_FAILS';

export const FETCH_FULL_EVENT_SUCCESS: string = 'FETCH_FULL_EVENT_SUCCESS';
export const FETCH_FULL_EVENT_FAILS: string = 'FETCH_FULL_EVENT_FAILS';

export const FETCH_SINGLE_EVENT_SUCCESS: string = 'FETCH_SINGLE_EVENT_SUCCESS';
export const FETCH_SINGLE_EVENT_FAILS: string = 'FETCH_SINGLE_EVENT_FAILS';

export const HANDLE_CHECK_BOX: string = 'HANDLE_CHECK_BOX';
export const HANDLE_IS_LOGIN: string = 'HANDLE_IS_LOGIN';

export const FETCH_PROFILE_SUCCESS: string = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILS: string = 'FETCH_PROFILE_FAILS';
export const EDIT_PROFILE: string = 'EDIT_PROFILE';

export const FETCH_PURCHASED_LIST_SUCCESS: string = 'FETCH_PURCHASED_LIST_SUCCESS';
export const FETCH_PURCHASED_LIST_FAILS: string = 'FETCH_PURCHASED_LIST_FAILS';

export const PURCHASE_EVENT_SUCCESS: string = 'PURCHASE_EVENT_SUCCESS';
export const PURCHASE_EVENT_FAILS: string = 'PURCHASE_EVENT_FAILS';

export const SEARCH: string = 'SEARCH';
export const HANDLE_BUY_ACCESS: string = 'HANDLE_BUY_ACCESS';
